<?php

namespace Tuto\AnimeauxBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * voitureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class voitureRepository extends EntityRepository
{
}
